# Valid TOML config file for Besu 25.7.0
data-path="/node/data"
logging="INFO"

# Network
network-id=3888
bootnodes=["enode://bd1782617ae151ba6da627a35a1babc0a40ae127a718cdc13322acb357411f095d56db6141c99d7f8b63b7ce896ffffbadea34a4471bca297c916a94e1d9b818@169.197.143.193:30303","enode://3ea0e690890c824cb39867c9da0e201764ecd2960c2609ecceb40b3e48d374424f791d32d87eaf7430249649b5c45673178454455b22b133458afc5ddf126c3a@169.197.143.209:30303"]
node-private-key-file="/node/data"

# Chain
genesis-file="/node/genesis.json"

# RPC Configuration
rpc-http-api=["ETH","NET","QBFT","WEB3","ADMIN"]
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-cors-origins=["*"]
rpc-gas-cap=50000000
host-allowlist=["*"]
revert-reason-enabled=true
data-storage-format="FOREST"

# WebSocket
rpc-ws-enabled=true

# Performance & Storage
data-storage-format="BONSAI"
bonsai-parallel-tx-processing-enabled=true
sync-mode="FULL"

# Metrics
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port="9545"
